---
- name: Install Mysql
  hosts: mysql
  vars_files:
    - ../infra-docker-registry/vars.yml
    - vars.yml
  vars:
   - registry_addr: "{{hostvars[groups['registry'][0]].hostname}}:{{registry_srv_port}}" 
  become: true
  tasks:
  - include: ../images/prepare_infra_images.yml
    when: force_update_images == True
  - name: Ensure docker is running
    become: yes
    service:
      name: docker
      state: started
  - name: Creates Mysql Data Directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0777
    loop:
      - "{{mysql_data_dir}}"

  - name: Copy Mysql Docker Compose Files
    template: 
      src: ./{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{mysql_compose_file}}"
  
  - name: Set timezone
    timezone:
      name: Asia/Shanghai


  - name: Start Mysql
    shell:
      cmd: "docker-compose -p gomono-infra-mysql -f /tmp/{{mysql_compose_file}} up -d"

  - name: Check Mysql Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Status'] == "running"
    retries: 10
    delay: 5
    loop:
      - "gomono-mysql"

- name: Install Mysql Slave
  hosts: mysql_slave
  vars_files:
    - ../infra-docker-registry/vars.yml
    - vars.yml
  vars:
   - registry_addr: "{{hostvars[groups['registry'][0]].hostname}}:{{registry_srv_port}}" 
  become: true
  tasks:
  - name: Creates Mysql Slave Data Directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0777
    loop:
      - "{{mysql_slave_data_dir}}"
      - "{{mysql_backup_data_dir}}"
      
  - name: Copy Mysql Slave Docker Compose Files
    template: 
      src: ./{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{mysql_slave_compose_file}}"
  
  - name: Start Mysql Slave
    shell:
      cmd: "docker-compose -p gomono-infra-mysql-slave -f /tmp/{{mysql_slave_compose_file}} up -d"

  - name: Check Mysql Slave Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Status'] == "running"
    retries: 10
    delay: 5
    loop:
      - "gomono-mysql-slave"
      - "gomono-mysql-backup"

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{mysql_compose_file}}"
  #     - "{{mysql_slave_compose_file}}"
