#########################################################################
# dockler私有仓库配置
#########################################################################
registry_srv_port: 8080  # docker私有仓库的服务端口 

