// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.21.12
// source: user/v1/users.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUsersServiceGetTrainingBalance = "/users.UsersService/GetTrainingBalance"

type UsersServiceHTTPServer interface {
	GetTrainingBalance(context.Context, *GetTrainingBalanceRequest) (*GetTrainingBalanceResponse, error)
}

func RegisterUsersServiceHTTPServer(s *http.Server, srv UsersServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/user/v1/getTrainingBalance", _UsersService_GetTrainingBalance0_HTTP_Handler(srv))
}

func _UsersService_GetTrainingBalance0_HTTP_Handler(srv UsersServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTrainingBalanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersServiceGetTrainingBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTrainingBalance(ctx, req.(*GetTrainingBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTrainingBalanceResponse)
		return ctx.Result(200, reply)
	}
}

type UsersServiceHTTPClient interface {
	GetTrainingBalance(ctx context.Context, req *GetTrainingBalanceRequest, opts ...http.CallOption) (rsp *GetTrainingBalanceResponse, err error)
}

type UsersServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUsersServiceHTTPClient(client *http.Client) UsersServiceHTTPClient {
	return &UsersServiceHTTPClientImpl{client}
}

func (c *UsersServiceHTTPClientImpl) GetTrainingBalance(ctx context.Context, in *GetTrainingBalanceRequest, opts ...http.CallOption) (*GetTrainingBalanceResponse, error) {
	var out GetTrainingBalanceResponse
	pattern := "/user/v1/getTrainingBalance"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersServiceGetTrainingBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
