version: "3.8"
services:
  nacos2:
    hostname: nacos2
    image: "{{registry_addr}}/{{nacos_image}}"
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "{{nacos2_conn_port1}}:7848"
      - "{{nacos2_srv_port}}:8848"
      - "{{nacos2_conn_port2}}:9848"
      - "{{nacos2_conn_port3}}:9849"
    env_file:
      - ./{{config_nacos}}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  