---
- name: Deploy Docker Container
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

    - name: Start Docker service
      service:
        name: docker
        state: started




