
server:
  grpc:
    addr: "0.0.0.0:{{biz_trainer_port}}"
    timeout: 1s
  # 本服务的服务注册地址
  register:
    endpoints:
      - "{{biz_trainer_host}}:{{biz_trainer_port}}"

public:
  adapter:
    database:  # 数据库服务地址
      driver: mysql
      source: "root:root@tcp({{mysql_host}}:23306)/test" # todo: 数据库名需要更新
    redis: # redis的服务地址
      addr: "{{redis_host}}:{{redis_srv_port}}"
      read_timeout: 0.2s
      write_timeout: 0.2s
  log:
    level: debug
    monitor:  # 日志服务地址
      endpoint: tcp://127.0.0.1:23224
    file:
      max_size:    50  # megabytes
      max_backups: 7    # file numbers
      max_age:     28   # days
      compress:    true
      local_time:  true

  registry:  # 注册中心的服务地址
    addrs:
      - "{{nacos_host}}:{{nacos1_srv_port}}"
      - "{{nacos_host}}:{{nacos2_srv_port}}"
      - "{{nacos_host}}:{{nacos3_srv_port}}"
  trace:  # 链路跟踪服务地址
    endpoint: "{{jaeger_host}}:{{jaeger_collector_otlp_http_port}}"

  discovery:  # 服务发现的服务地址
    endpoints:
      - "{{nacos_host}}:{{nacos1_srv_port}}"