---
- name: Install Jaeger
  hosts: jaeger
  vars_files:
    - ../infra-docker-registry/vars.yml
    - vars.yml
  vars:
   - registry_addr: "{{hostvars[groups['registry'][0]].hostname}}:{{registry_srv_port}}" 
  become: true
  tasks:
  - name: Ensure docker is running
    become: yes
    service:
      name: docker
      state: started
  - name: Copy Jaeger Docker-Compose Files
    template: 
      src: ./{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{jaeger_compose_file}}"
  
  - name: Start Jaeger
    shell:
      cmd: "docker-compose -p gomono-infra-jaeger -f /tmp/{{jaeger_compose_file}} up -d"

  - name: Check Jaeger Running Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Status'] == "running"
    retries: 10
    delay: 5
    loop:
      - "gomono-jaeger"

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{jaeger_compose_file}}"
