
#########################################################################
# 基础设施镜像相关配置
#########################################################################
prometheus_image: prom/prometheus:latest
jaeger_image: jaegertracing/all-in-one:1.52 # dockerproxy.com/jaegertracing/all-in-one:1.52
grafana_image: grafana/grafana:latest
infra_images_list:   # 通过在线下载的基础设施的镜像列表
  - "{{prometheus_image}}"
  - "{{jaeger_image}}"
  - "{{grafana_image}}"

delete_download_images: true  # 是否删除本地已上传到私有仓库的基础设施镜像
force_update_images: false  # 是否下载或更新基础设施镜像

#########################################################################
# prometheus相关配置
#########################################################################
prometheus_compose_file: docker_compose_prometheus_grafana.yml  # prometheus的compose文件
prometheus_srv_port: 9090  # prometheus的服务端口
grafana_srv_port: 3000 # grafana的服务端口
config_prometheus: prometheus.yml  # prometheus的配置文件名称

#########################################################################
# 链路跟踪服务端jaeger相关配置
#########################################################################
jaeger_compose_file: docker_compose_jaeger.yml
jaeger_host: 192.168.72.84
jaeger_thrift_compact_port: 6831  # UDP agent accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
jaeger_thrift_binary_port: 6832	 # UDP agent accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
jaeger_agent_zipkin_port: 5775	 # UDP agent (deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
jaeger_agent_configs_port: 5778	 # HTTP agent serve configs (sampling, etc.)
jaeger_query_port: 16686	 # HTTP query serve frontend
jaeger_collector_otlp_grpc_port: 4317	 # HTTP collector accept OpenTelemetry Protocol (OTLP) over gRPC
jaeger_collector_otlp_http_port: 4318	 # HTTP collector accept OpenTelemetry Protocol (OTLP) over HTTP
jaeger_collector_direct_port: 14268	 # HTTP collector accept jaeger.thrift directly from clients
jaeger_collector_model_port: 14250	 # HTTP collector accept model.proto
jaeger_collector_zipkin_port: 9411	 # HTTP collector Zipkin compatible endpoint (optional)


