---
- name: Ensure docker is running
  become: yes
  service:
    name: docker
    state: started
    
- name: Tag Images
  command: "docker tag {{item}} {{registry_addr}}/{{item}}"
  loop: 
    "{{biz_images_list}}"

- name: Push Images
  command: "docker push {{registry_addr}}/{{item}}"
  loop: 
    "{{biz_images_list}}"

- name: Remove Local Images
  command: "docker rmi {{registry_addr}}/{{item}}"
  loop: 
    "{{biz_images_list}}"
  when: delete_download_images == True
