
#########################################################################
# 业务和docker相关的配置
#########################################################################
biz_stack: bizstack # docker stack的名称前缀
bff_image: app/bff-gomono:latest
bff_compose_file: docker_compose_bff.yml # bff服务的docker-compose文件
biz_images_list: 
 - "{{bff_image}}"

force_update_images: true  # 是否下载或更新基础设施镜像

#########################################################################
# bff相关配置
#########################################################################
mode: develop  # 运行模式 develop test product  bff也使用该字段
bff_host: 192.168.72.84 # bff服务的地址
bff_port: 8200   # bff服务端口号
bff_data_dir: /gomono/bff # bff数据的目录
bff_config_dir: "{{bff_data_dir}}/config" # bff配置目录
bff_log_dir: "{{bff_data_dir}}/log"  # bff日志目录




