
public:
  adapter:
    database:
      driver: mysql
      source: "root:root@tcp({{mysql_host}}:23306)/test"
    redis:
      addr: 127.0.0.1:26379
      read_timeout: 0.2s
      write_timeout: 0.2s
  log:
    level: debug
    monitor:
      endpoint: tcp://127.0.0.1:23224
    file:
      max_size:    100  # megabytes
      max_backups: 7    # file numbers
      max_age:     28   # days
      compress:    true

  registry: 
    addrs:
      - "{{nacos1_host}}:{{nacos1_srv_port}}"
      - "{{nacos2_host}}:{{nacos2_srv_port}}"
      - "{{nacos3_host}}:{{nacos3_srv_port}}"
  trace:
    endpoint: 127.0.0.1:2379

  discovery:
    endpoints:
      - "{{nacos1_host}}:{{nacos1_srv_port}}"
