---
- name: Get Docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Install Gateway
  hosts: gateway
  vars_files:
    - vars.yml
  vars:
    - registry_addr: "{{registry_hostname.stdout}}:{{registry_srv_port}}"
  become: true
  tasks:
  - name: Creates Gateway Data Directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0777
    loop:
      - "{{gateway_data_dir}}"
      - "{{gateway_config_dir}}"

  - name: Copy Gateway Docker-Compose Files
    template: 
      src: ../tmpl/{{ item }}
      dest: "{{gateway_data_dir}}/{{ item }}"
      force: true
    loop:
      - "{{gateway_compose_file}}"
  - name: Copy Gateway config Files
    template: 
      src: ../../config/{{ item }}
      dest: "{{gateway_config_dir}}/{{ item }}"
      force: true
    loop:
      - "gateway.yaml"
      - "public.yaml"

  - name: Stop Gateway
    shell:
      cmd: "docker-compose -p gatway -f {{gateway_data_dir}}/{{gateway_compose_file}} down"

  - name: Start Gateway
    shell:
      cmd: "docker-compose -p gatway -f {{gateway_data_dir}}/{{gateway_compose_file}} up -d"

  - name: Check Gateway Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Status'] == "running"
    retries: 10
    delay: 5
    loop:
      - "gateway"

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{prometheus_compose_file}}"
