---
- name: Get docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Install Prometheus & Grafana
  hosts: prometheus
  vars_files:
    - vars.yml
  vars:
    - registry_addr: "{{registry_hostname.stdout}}:{{registry_srv_port}}"
  become: true
  tasks:
  - name: Copy Prometheus&Grafana Docker-Compose Files
    template: 
      src: ../{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{prometheus_compose_file}}"
      - "{{config_prometheus}}"
  
  - name: Start Prometheus & Grafana
    shell:
      cmd: "docker-compose -f /tmp/{{prometheus_compose_file}} up -d"

  - name: Check Prometheus & Grafana Running Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Status'] == "running"
    retries: 10
    delay: 5
    loop:
      - "prometheus"
      - "grafana"

  - name: Delete docker-compose.yml
    file: 
      dest: /tmp/{{ item }}
      state: absent
    loop:
      - "{{prometheus_compose_file}}"
