---
- name: Get Docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Install Gateway
  hosts: gateway
  vars_files:
    - vars.yml
  vars:
    - registry_addr: "{{registry_hostname.stdout}}:{{registry_srv_port}}"
  become: true
  tasks:
  - name: Ensure docker is running
    become: yes
    service:
      name: docker
      state: started
  - name: Creates Gateway Data Directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0777
    loop:
      - "{{gateway_data_dir}}"
      - "{{gateway_config_dir}}"

  - name: Copy Gateway Docker-Compose Files
    template: 
      src: ../tmpl/{{ item }}
      dest: "{{gateway_data_dir}}/{{ item }}"
      force: true
    loop:
      - "{{gateway_compose_file}}"
  - name: Copy Gateway config Files
    template: 
      src: ../tmpl/{{ item }}
      dest: "{{gateway_config_dir}}/{{ item }}"
      force: true
    loop:
      - "gateway.yaml"
      - "public.yaml"
  - name: Backup Gateway config Files
    delegate_to: localhost
    template: 
      src: ../tmpl/{{ item }}
      dest: ../../standalone/config/{{ item }}
      force: true
      mode: 0777
    loop:
      - "gateway.yaml"
      - "public.yaml"

  - name: Start Gateway
    shell:
      # cmd: "docker-compose -p biz -f {{gateway_data_dir}}/{{gateway_compose_file}} up -d"
      cmd: "docker stack deploy --compose-file  {{gateway_data_dir}}/{{gateway_compose_file}}  {{biz_stack}}"

  - name: Check Gateway Status
    docker_swarm_service_info:
      name: "{{item}}"
    register: result
    until: (result.exists == true) and (result.failed == false)
    retries: 10
    delay: 5
    loop:
      - "{{biz_stack}}_gateway"

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{prometheus_compose_file}}"
