---
- name: Get Docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Install Nacos
  hosts: nacos
  vars_files:
    - vars.yml
  vars:
    - registry_addr: "{{registry_hostname.stdout}}:{{registry_srv_port}}"
  become: true
  tasks:
  - name: Copy Nacos Docker-Compose & Config Files
    template: 
      src: ../tmpl/{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{nacos1_compose_file}}"
      - "{{nacos2_compose_file}}"
      - "{{nacos3_compose_file}}"
      - "{{nacos_mysql_compose_file}}"
      - "{{config_nacos_mysql}}"
      - "{{config_nacos}}"
  
  - name: Stop Nacos-MySQL
    shell:
      cmd: "docker-compose -p infra -f /tmp/{{nacos_mysql_compose_file}} down"
    when: (nacos_mysql_host == ansible_hostname) or (nacos_mysql_host == ansible_host)
  - name: Stop Nacos ...
    shell:
      cmd: "docker-compose -p infra -f /tmp/{{item.1}} down"
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together: 
      - "{{[nacos1_host,nacos2_host,nacos3_host]}}"
      - "{{[nacos1_compose_file,nacos2_compose_file,nacos3_compose_file]}}"

  - name: Start Nacos-MySQL
    shell:
      cmd: "docker-compose -p infra -f /tmp/{{nacos_mysql_compose_file}} up -d"
    when: (nacos_mysql_host == ansible_hostname) or (nacos_mysql_host == ansible_host)

  - name: Check Nacos-MySQL Running Status
    docker_container_info:
      name: "{{item}}"
    register: result
    until: result.container['State']['Health']['Status'] == "healthy"
    retries: 10
    delay: 5
    when: (nacos_mysql_host == ansible_hostname) or (nacos_mysql_host == ansible_host)
    loop:
      - "nacos-mysql"


  - name: Start Nacos ...
    shell:
      cmd: "docker-compose -p infra -f /tmp/{{item.1}} up -d"
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together: 
      - "{{[nacos1_host,nacos2_host,nacos3_host]}}"
      - "{{[nacos1_compose_file,nacos2_compose_file,nacos3_compose_file]}}"

  - name: Check Nacos Running Status
    docker_container_info:
      name: "{{item.1}}"
    register: result
    until: result.container['State']['Health']['Status'] == "healthy"
    retries: 15
    delay: 5
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together:
      - "{{[nacos1_host,nacos2_host,nacos3_host]}}"
      - ["nacos1","nacos2","nacos3"]

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{nacos1_compose_file}}"
  #     - "{{nacos2_compose_file}}"
  #     - "{{nacos3_compose_file}}"
  #     - "{{nacos_mysql_compose_file}}"
