---
- name: Get Docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Prepare Infra Images
  hosts: images
  vars_files:
    - vars.yml
  vars:
    - registry_addr: "{{registry_hostname.stdout}}:{{registry_srv_port}}"
  tasks:
  - name: Ensure docker is running
    become: yes
    service:
      name: docker
      state: started
  - name: Tag Images
    command: "docker tag {{item}} {{registry_addr}}/{{item}}"
    loop: 
      "{{biz_images_list}}"

  - name: Push Images
    command: "docker push {{registry_addr}}/{{item}}"
    loop: 
      "{{biz_images_list}}"

  - name: Remove Local Images
    command: "docker rmi {{registry_addr}}/{{item}}"
    loop: 
      "{{biz_images_list}}"
    when: delete_download_images == True
  