---
- name: Get Docker Image Registry Hostname
  hosts: registry
  tasks:
  - name: get registry hostname
    command: cat /etc/hostname
    register: registry_hostname

- name: Prepare Infra Images
  hosts: master
  vars_files:
    - vars.yml
  tasks:
  - name: Stop Nacos-MySQL
    shell:
      cmd: "docker-compose -f /tmp/{{nacos_mysql_compose_file}} down"
    when: nacos_mysql_host == ansible_hostname
