version: "3.8"
services:
  gateway:
    hostname: gateway
    image: "{{registry_addr}}/{{gateway_image}}"
    container_name: gateway
    ports:
      - "{{proxy_port1}}:{{proxy_port1}}"
      - "{{proxy_port2}}:{{proxy_port2}}"
    environment:
      - "MODE={{mode}}"
      - "DEBUG={{debug}}"
      - "PROXYADDRS={{proxy_addrs}}"
      - "NACOS_HOST={{nacos_host}}"
      - "NACOS_PORT={{nacos1_srv_port}}"
    volumes:
      - "{{gateway_config_dir}}:/bin/config"
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'