version: "3.8"
services:
  gateway:
    hostname: gateway
    image: "{{registry_addr}}/{{gateway_image}}"
    container_name: ggateway
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "{{nacos3_conn_port1}}:7848"
    env:
      - MODE: develop
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sSL 'http://localhost:8848/nacos/actuator/health' || exit 1"]
      timeout: 2s
      interval: 10s
      retries: 50
      start_period: 15s