version: "3.8"
services:
  mysql:
    container_name: nacos-mysql
    image: "{{registry_addr}}/{{nacos_mysql_image}}"
    env_file:
      - ./{{config_nacos_mysql}}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "{{nacos_mysql_port}}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    extra_hosts:
      - 'host.docker.internal:host-gateway'