version: "3.8"
services:
  nacos3:
    hostname: nacos3
    image: "{{registry_addr}}/{{nacos_image}}"
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "{{nacos3_conn_port1}}:7848"
      - "{{nacos3_srv_port}}:8848"
      - "{{nacos3_conn_port2}}:9848"
      - "{{nacos3_conn_port3}}:9849"
    env_file:
      - ./{{config_nacos}}
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sSL 'http://localhost:8848/nacos/actuator/health' || exit 1"]
      timeout: 2s
      interval: 10s
      retries: 50
      start_period: 15s
    extra_hosts:
      - 'host.docker.internal:host-gateway'