version: "3.8"
services:
  gateway:
    hostname: gateway
    image: "{{registry_addr}}/{{gateway_image}}"
    container_name: gateway
    ports:
      - "{{proxy_port1}}:{{proxy_port1}}"
      - "{{proxy_port2}}:{{proxy_port2}}"
    environment:
      - MODE={{mode}}
      - DEBUG={{mode}}
      - PROXYADDRS={{proxy_addrs}}
      - NACOS_HOST={{nacos1_host}}
      - NACOS_PORT={{nacos1_srv_port}}
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -sSL 'http://localhost:8848/nacos/actuator/health' || exit 1"]
      timeout: 2s
      interval: 10s
      retries: 50
      start_period: 15s