version: "3.8"
services:
  gateway:
    hostname: gateway
    image: "{{registry_addr}}/{{gateway_image}}"
    ports:
      - "{{proxy_port1}}:{{proxy_port1}}"
      - "{{proxy_port2}}:{{proxy_port2}}"
    environment:
      - "MODE={{mode}}"
      - "DEBUG={{debug}}"
      - "PROXYADDRS={{proxy_addrs}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{gateway_config_dir}}:/bin/config"
      - "{{gateway_log_dir}}:/bin/log"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s