
public:
  adapter:
    database:
      driver: mysql
      source: "root:root@tcp(192.168.72.84:23306)/test"
    redis:
      addr: 127.0.0.1:26379
      read_timeout: 0.2s
      write_timeout: 0.2s
  log:
    level: debug
    monitor:
      endpoint: tcp://127.0.0.1:23224
    file:
      max_size:    50  # megabytes
      max_backups: 7    # file numbers
      max_age:     28   # days
      compress:    true
      local_time:  true

  registry: 
    addrs:
      - "192.168.72.84:8848"
      - "192.168.72.84:8858"
      - "192.168.72.84:8868"
  trace:
    endpoint: "192.168.72.84:4318"

  discovery:
    endpoints:
      - "192.168.72.84:8848"

  gateway_register:
    endpoints:
      - "192.168.72.84:8180"