---
- name: Install Nacos
  hosts: nacos
  vars_files:
    - ../infra-docker-registry/vars.yml
    - vars.yml
  vars:
   - registry_addr: "{{hostvars[groups['registry'][0]].hostname}}:{{registry_srv_port}}" 
  become: true
  tasks:
  - include: ../images/prepare_infra_images.yml
    when: force_update_images == True
  - name: Ensure docker is running
    become: yes
    service:
      name: docker
      state: started
  - name: Copy Nacos Docker-Compose & Config Files
    template: 
      src: ./{{ item }}
      dest: /tmp/{{ item }}
      force: true
    loop:
      - "{{nacos_compose_file}}"
      - "{{config_nacos_mysql}}"
      - "{{config_nacos}}"
  
  - name: Creates Nacos Directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0777
    loop:
      - "{{nacos_log_dir}}"

  - name: Stop Nacos ...
    shell:
      cmd: "docker-compose -p gomono-infra-nacos -f /tmp/{{item.1}} down"
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together: 
      - "{{[nacos_host]}}"
      - "{{[nacos_compose_file]}}"

  - name: Start Nacos ...
    shell:
      cmd: "docker-compose -p gomono-infra-nacos -f /tmp/{{item.1}} up -d"
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together: 
      - "{{[nacos_host]}}"
      - "{{[nacos_compose_file]}}"

  - name: Check Nacos Running Status
    docker_container_info:
      name: "{{item.1}}"
    register: result
    until: result.container['State']['Health']['Status'] == "healthy"
    retries: 15
    delay: 5
    when: (item.0 == ansible_hostname) or (item.0 == ansible_host)
    with_together:
      - "{{[nacos_host,nacos_host,nacos_host]}}"
      - ["gomono-nacos-mysql","gomono-nacos1","gomono-nacos2","gomono-nacos3"]

  # - name: Delete docker-compose.yml
  #   file: 
  #     dest: /tmp/{{ item }}
  #     state: absent
  #   loop:
  #     - "{{nacos_compose_file}}"
