#########################################################################
# 基础设施镜像相关配置
#########################################################################
nacos_image: nacos/nacos-server:latest
nacos_mysql_image: nacos/mysql:8.0.31

infra_images_list:   # 通过在线下载的基础设施的镜像列表
  - "{{nacos_image}}"

local_infra_images_list: # 需要本地打包的基础设施的镜像列表
  - "{{nacos_mysql_image}}"
local_infra_images_dockerfile_list: # 注意顺序保存和 local_infra_images_list 一致
  - "dockerfile.nacos_mysql"

delete_download_images: true  # 是否删除本地已上传到私有仓库的基础设施镜像
force_update_images: false  # 是否下载或更新基础设施镜像

#########################################################################
# nacos相关配置
#########################################################################
nacos_compose_file: docker_compose_nacos.yml  # nacos1的compose文件
config_nacos_mysql: config_nacos_mysql.env # nacos使用的数据库的配置
config_nacos: config_nacos.env # nacos的配置文件， 【注意】： 其中的服务地址配置如果配置为域名不通的话， 可配置为ip直接访问
nacos_mysql_port: 13306 # nacos使用的mysql的服务端口
# 如果配置主机名不通， 需检查宿主机的/etc/resolv.conf的配置,确保nslookup能查到解析
nacos_mysql_host: 192.168.72.84 # 部分情况如果配置为mysql服务主机名，docker内置dns服务会解析失败，此时可以配置为ip地址； nacos使用的mysql的服务地址，该主机的dns需要配置在部署nacos的机子上, 并在ansible主机清单维护

# 如果nacos运行在同一节点，务必保证个nacos的端口号不重复
nacos_host: 192.168.72.84 # nacos1的服务地址，该主机的dns需要配置在部署nacos/prometheus的机子上, 并在ansible主机清单维护
nacos1_conn_port1: 7848
nacos1_conn_port2: 9848
nacos1_conn_port3: 9849
nacos1_srv_port: 8848
nacos2_conn_port1: 7858
nacos2_conn_port2: 9858
nacos2_conn_port3: 9859
nacos2_srv_port: 8858
nacos3_conn_port1: 7868
nacos3_conn_port2: 9868
nacos3_conn_port3: 9869
nacos3_srv_port: 8868

nacos_data_dir: /gomono/gateway # 网关数据的目录
nacos_log_dir: "{{nacos_data_dir}}/log" # 网关日志目录