---
- hosts: all
  gather_facts: no
 
  tasks:
  - name: install ssh key  # 复制管理主机的公钥到所有节点上
    authorized_key: 
      user: "{{ansible_ssh_user}}"
      key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
      state: present