// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: gateway-gomono/internal/conf/gateway.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proxy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug bool     `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	Addrs []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gomono_internal_conf_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gomono_internal_conf_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_gateway_gomono_internal_conf_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Proxy) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Proxy) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

var File_gateway_gomono_internal_conf_gateway_proto protoreflect.FileDescriptor

var file_gateway_gomono_internal_conf_gateway_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x67, 0x6f, 0x6d, 0x6f, 0x6e, 0x6f,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x22, 0x33, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x69, 0x71, 0x69, 0x6e, 0x66, 0x65, 0x6e,
	0x67, 0x31, 0x2f, 0x67, 0x6f, 0x4d, 0x6f, 0x6e, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x67, 0x6f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_gomono_internal_conf_gateway_proto_rawDescOnce sync.Once
	file_gateway_gomono_internal_conf_gateway_proto_rawDescData = file_gateway_gomono_internal_conf_gateway_proto_rawDesc
)

func file_gateway_gomono_internal_conf_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gomono_internal_conf_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gomono_internal_conf_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_gomono_internal_conf_gateway_proto_rawDescData)
	})
	return file_gateway_gomono_internal_conf_gateway_proto_rawDescData
}

var file_gateway_gomono_internal_conf_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_gomono_internal_conf_gateway_proto_goTypes = []interface{}{
	(*Proxy)(nil), // 0: kratos.config.gateway.Proxy
}
var file_gateway_gomono_internal_conf_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gomono_internal_conf_gateway_proto_init() }
func file_gateway_gomono_internal_conf_gateway_proto_init() {
	if File_gateway_gomono_internal_conf_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_gomono_internal_conf_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proxy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_gomono_internal_conf_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gomono_internal_conf_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gomono_internal_conf_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gomono_internal_conf_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gomono_internal_conf_gateway_proto = out.File
	file_gateway_gomono_internal_conf_gateway_proto_rawDesc = nil
	file_gateway_gomono_internal_conf_gateway_proto_goTypes = nil
	file_gateway_gomono_internal_conf_gateway_proto_depIdxs = nil
}
